name: Release

on:
  push:
    branches:
      - main  # Укажите ветку, на которой будут создаваться релизы

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Получить всю историю коммитов для стандартной версии

      # Шаг 2: Установка Node.js (для standard-version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Укажите версию Node.js

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 4: Генерация CHANGELOG.md и создание тега
      - name: Generate CHANGELOG and tag
        run: npx standard-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к репозиторию

      # Шаг 5: Отправка изменений в репозиторий
      - name: Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --follow-tags origin main